### ISSUE TITLE
Deliverable 1

### ISSUE THREAD

**Issue by bfiliks** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bfiliks#1]
This is a screenshot for deliverable 1
![Deliverable 1](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bfiliks/assets/37164388/20511fec-b220-4e2c-8989-f37c3a60a9cd)

**Comment by instructorc** [comment]
Deliverable #1 met!
