### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by bfiliks** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bfiliks#2]
git log displaying all my git commands.
![Deliverable 2](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bfiliks/assets/37164388/84979532-38d2-4954-8dda-fff0ba3bb74a)

**Comment by instructorc** [comment]
Deliverable #2 met!
